_attn_implementation_autoset:
    value: true
_name_or_path:
    value: /ceph/hpc/data/s24o01-42-users/translation_optimization/trl/trained_models/Curriculum_DPO_models/GaMS-9B-DPO-Curri-0
_wandb:
    value:
        cli_version: 0.19.7
        m:
            - "1": eval/rewards/rejected
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": eval/rewards/accuracies
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/samples_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/rewards/accuracies
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/logits/rejected
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/logits/rejected
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/logps/rejected
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/rewards/rejected
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/logits/chosen
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/logps/chosen
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/rewards/chosen
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/runtime
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/logps/rejected
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/grad_norm
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/rewards/margins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/rewards/margins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/logits/chosen
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/logps/chosen
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/rewards/chosen
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/steps_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "3":
                - 7
                - 13
                - 19
                - 23
                - 55
                - 62
                - 66
            "4": 3.10.12
            "5": 0.19.7
            "6": 4.51.3
            "8":
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.19.7
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Gemma2ForCausalLM
attention_bias:
    value: false
attention_dropout:
    value: 0
attn_logit_softcapping:
    value: 50
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
beta:
    value: 0.2
bf16:
    value: true
bf16_full_eval:
    value: true
bos_token_id:
    value: 2
cache_implementation:
    value: hybrid
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_num_proc:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_dropout:
    value: true
disable_tqdm:
    value: false
discopop_tau:
    value: 0.05
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 1
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 209
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
f_alpha_divergence_coef:
    value: 1
f_divergence_type:
    value: reverse_kl
final_logit_softcapping:
    value: 30
finetuning_task:
    value: null
force_use_ref_model:
    value: false
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
generate_during_eval:
    value: false
generation_config:
    value:
        _from_model_config: true
        assistant_confidence_threshold: 0.4
        assistant_early_exit: null
        assistant_lookbehind: 10
        bad_words_ids: null
        begin_suppress_tokens: null
        bos_token_id: 2
        cache_config: null
        cache_implementation: hybrid
        constraints: null
        decoder_start_token_id: null
        disable_compile: false
        diversity_penalty: 0
        do_sample: false
        dola_layers: null
        early_stopping: false
        encoder_no_repeat_ngram_size: 0
        encoder_repetition_penalty: 1
        eos_token_id: 1
        epsilon_cutoff: 0
        eta_cutoff: 0
        exponential_decay_length_penalty: null
        force_words_ids: null
        forced_bos_token_id: null
        forced_decoder_ids: null
        forced_eos_token_id: null
        guidance_scale: null
        is_assistant: false
        length_penalty: 1
        low_memory: null
        max_length: 20
        max_matching_ngram_size: null
        max_new_tokens: null
        max_time: null
        min_length: 0
        min_new_tokens: null
        min_p: null
        no_repeat_ngram_size: 0
        num_assistant_tokens: 20
        num_assistant_tokens_schedule: constant
        num_beam_groups: 1
        num_beams: 1
        num_return_sequences: 1
        output_attentions: false
        output_hidden_states: false
        output_logits: null
        output_scores: false
        pad_token_id: 0
        penalty_alpha: null
        prefill_chunk_size: null
        prompt_lookup_num_tokens: null
        remove_invalid_values: false
        renormalize_logits: false
        repetition_penalty: 1
        return_dict_in_generate: false
        return_legacy_cache: null
        sequence_bias: null
        stop_strings: null
        suppress_tokens: null
        target_lookbehind: 10
        temperature: null
        token_healing: false
        top_k: 50
        top_p: null
        transformers_version: 4.52.4
        typical_p: 1
        use_cache: true
        watermarking_config: null
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
head_dim:
    value: 256
hidden_act:
    value: gelu_pytorch_tanh
hidden_activation:
    value: gelu_pytorch_tanh
hidden_size:
    value: 3584
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 14336
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_pad_token_id:
    value: -100
label_smoothing:
    value: 0
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 4e-07
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: training_run/curri-1_r-64_lr-4e-07_b-0.2/runs/Jun09_01-29-56_gn49
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
loss_type:
    value: sigmoid
lr_scheduler_kwargs:
    value:
        min_lr: 4e-08
lr_scheduler_type:
    value: cosine_with_min_lr
max_completion_length:
    value: null
max_grad_norm:
    value: 1
max_length:
    value: 2048
max_position_embeddings:
    value: 8192
max_prompt_length:
    value: null
max_steps:
    value: -1
metric_for_best_model:
    value: eval_loss
min_length:
    value: 0
model/num_parameters:
    value: 9457778176
model_adapter_name:
    value: null
model_init_kwargs:
    value: null
model_type:
    value: gemma2
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 16
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 42
num_key_value_heads:
    value: 8
num_return_sequences:
    value: 1
num_train_epochs:
    value: 3
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: training_run/curri-1_r-64_lr-4e-07_b-0.2
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 0
padding_free:
    value: false
padding_value:
    value: null
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: /ceph/hpc/data/s24o01-42-users/translation_optimization/trl/trained_models/Curriculum_DPO_models/GaMS-9B-DPO-Curri-0
            bias: none
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 128
            lora_bias: false
            lora_dropout: 0.1
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            r: 64
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - down_proj
                - o_proj
                - q_proj
                - up_proj
                - gate_proj
                - k_proj
                - v_proj
            task_type: CAUSAL_LM
            use_dora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 1
per_device_train_batch_size:
    value: 1
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
precompute_ref_batch_size:
    value: null
precompute_ref_log_probs:
    value: false
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
query_pre_attn_scalar:
    value: 256
ray_scope:
    value: last
ref_adapter_name:
    value: null
ref_model_init_kwargs:
    value: null
ref_model_mixup_alpha:
    value: 0.9
ref_model_sync_steps:
    value: 64
reference_free:
    value: false
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-06
rope_theta:
    value: 10000
rpo_alpha:
    value: null
run_name:
    value: Curri-1-DPO_r-64_lr-4e-07_e-3_b-0.2
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 209
save_strategy:
    value: steps
save_total_limit:
    value: 10
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
sliding_window:
    value: 4096
sliding_window_size:
    value: 4096
suppress_tokens:
    value: null
sync_ref_model:
    value: false
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
tools:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: float32
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tp_size:
    value: 0
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.51.3
truncation_mode:
    value: keep_end
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_logits_to_keep:
    value: false
use_mps_device:
    value: false
use_num_logits_to_keep:
    value: false
use_weighting:
    value: false
vocab_size:
    value: 256000
warmup_ratio:
    value: 0
warmup_steps:
    value: 418
weight_decay:
    value: 0.1
